#!/usr/bin/env python3
"""
analyze_security.py

Reads detection_log.csv and performance_log.csv generated by security_system.py
and produces:
- Performance metrics (Accuracy, Precision, Recall, F1, FAR, FRR)
- FPS vs Time graph
- Faces Detected vs Time graph
- Confidence Score Distribution histogram
- Confusion Matrix
- FAR vs Threshold graph
- Precision-Recall curve

Usage:
    python analyze_security.py --detection_log logs/detection_log.csv \
                               --performance_log logs/performance_log.csv \
                               --output_dir analysis_output
"""

import argparse
import os
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.metrics import (accuracy_score, precision_score, recall_score,
                             f1_score, confusion_matrix, precision_recall_curve)
from datetime import datetime
import warnings
warnings.filterwarnings('ignore')

def load_data(detection_csv, performance_csv):
    """Load detection and performance logs."""
    try:
        det_df = pd.read_csv(detection_csv)
        det_df['timestamp'] = pd.to_datetime(det_df['timestamp'])
    except Exception as e:
        print(f"Error loading detection log: {e}")
        return None, None

    perf_df = None
    if performance_csv and os.path.exists(performance_csv):
        try:
            perf_df = pd.read_csv(performance_csv)
            perf_df['timestamp'] = pd.to_datetime(perf_df['timestamp'])
        except Exception as e:
            print(f"Error loading performance log: {e}")

    return det_df, perf_df

def compute_metrics(det_df):
    """Compute accuracy, precision, recall, f1, far, frr."""
    # Filter out rows where true_label is placeholder "?"
    if 'true_label' in det_df.columns:
        mask = det_df['true_label'] != '?'
        if not mask.all():
            print(f"Warning: {len(det_df) - mask.sum()} rows have placeholder '?' in true_label. These will be ignored.")
            det_df = det_df[mask]

    if det_df.empty:
        raise ValueError("No valid ground truth rows after removing placeholders. Please replace '?' with actual labels.")

    # Check that we have both classes
    unique_true = det_df['true_label'].unique()
    unique_pred = det_df['predicted_label'].unique()
    print(f"Unique true labels: {unique_true}")
    print(f"Unique predicted labels: {unique_pred}")

    if len(unique_true) < 2:
        raise ValueError(f"True labels contain only one class: {unique_true}. Need both 'authorized' and 'unauthorized'.")

    # Map labels to binary: authorized=1, unauthorized=0
    true_binary = det_df['true_label'].apply(lambda x: 1 if x == 'authorized' else 0)
    pred_binary = det_df['predicted_label'].apply(lambda x: 1 if x == 'authorized' else 0)

    acc = accuracy_score(true_binary, pred_binary)
    prec = precision_score(true_binary, pred_binary, zero_division=0)
    rec = recall_score(true_binary, pred_binary, zero_division=0)
    f1 = f1_score(true_binary, pred_binary, zero_division=0)

    tn, fp, fn, tp = confusion_matrix(true_binary, pred_binary).ravel()
    far = fp / (fp + tn) if (fp + tn) > 0 else 0
    frr = fn / (fn + tp) if (fn + tp) > 0 else 0

    metrics = {
        'Accuracy': acc,
        'Precision': prec,
        'Recall': rec,
        'F1-score': f1,
        'FAR': far,
        'FRR': frr,
        'TP': tp,
        'TN': tn,
        'FP': fp,
        'FN': fn
    }
    return metrics

def plot_fps_vs_time(perf_df, output_dir):
    """Generate FPS vs Time graph."""
    if perf_df is None or perf_df.empty:
        print("No performance data to plot FPS.")
        return
    plt.figure(figsize=(10, 4))
    plt.plot(perf_df['timestamp'], perf_df['fps'], marker='o', linestyle='-')
    plt.xlabel('Time')
    plt.ylabel('Frames per Second (FPS)')
    plt.title('FPS vs Time')
    plt.grid(True)
    plt.xticks(rotation=45)
    plt.tight_layout()
    plt.savefig(os.path.join(output_dir, 'fps_vs_time.png'))
    plt.close()

def plot_faces_vs_time(det_df, output_dir, bin_seconds=60):
    """Generate Faces Detected vs Time graph."""
    if det_df.empty:
        return
    # Resample by time bin
    det_df.set_index('timestamp', inplace=True)
    faces_per_bin = det_df.resample(f'{bin_seconds}S').size()
    plt.figure(figsize=(10, 4))
    plt.plot(faces_per_bin.index, faces_per_bin.values)
    plt.xlabel('Time')
    plt.ylabel('Number of Faces Detected')
    plt.title(f'Faces Detected per {bin_seconds} Seconds')
    plt.grid(True)
    plt.tight_layout()
    plt.savefig(os.path.join(output_dir, 'faces_vs_time.png'))
    plt.close()
    det_df.reset_index(inplace=True)

def plot_confidence_histogram(det_df, output_dir):
    """Generate confidence score distribution histogram."""
    if 'confidence' not in det_df.columns:
        print("No confidence column in detection log.")
        return
    # Filter out rows with placeholder true_label for histogram
    if 'true_label' in det_df.columns:
        mask = det_df['true_label'] != '?'
        plot_df = det_df[mask]
    else:
        plot_df = det_df

    if plot_df.empty:
        print("No valid rows for confidence histogram.")
        return

    plt.figure(figsize=(8, 5))
    sns.histplot(data=plot_df, x='confidence', hue='true_label', kde=True, bins=30)
    plt.xlabel('Confidence Score')
    plt.ylabel('Frequency')
    plt.title('Confidence Distribution by True Label')
    plt.legend(title='True Label')
    plt.tight_layout()
    plt.savefig(os.path.join(output_dir, 'confidence_histogram.png'))
    plt.close()

def plot_confusion_matrix(metrics, output_dir):
    """Generate confusion matrix heatmap."""
    cm = np.array([[metrics['TN'], metrics['FP']],
                   [metrics['FN'], metrics['TP']]])
    plt.figure(figsize=(6, 5))
    sns.heatmap(cm, annot=True, fmt='d', cmap='Blues',
                xticklabels=['Unauthorized', 'Authorized'],
                yticklabels=['Unauthorized', 'Authorized'])
    plt.xlabel('Predicted')
    plt.ylabel('True')
    plt.title('Confusion Matrix')
    plt.tight_layout()
    plt.savefig(os.path.join(output_dir, 'confusion_matrix.png'))
    plt.close()

def plot_far_vs_threshold(det_df, output_dir):
    """Generate FAR vs Threshold graph."""
    if 'confidence' not in det_df.columns:
        print("No confidence column; cannot plot FAR vs Threshold.")
        return
    # Filter out placeholder rows
    mask = det_df['true_label'] != '?'
    plot_df = det_df[mask]
    if plot_df.empty:
        print("No valid rows for FAR vs Threshold.")
        return

    true_binary = (plot_df['true_label'] == 'authorized').astype(int)
    thresholds = np.linspace(0, 1, 100)
    far_list = []
    frr_list = []
    for th in thresholds:
        pred = (plot_df['confidence'] >= th).astype(int)
        tn, fp, fn, tp = confusion_matrix(true_binary, pred).ravel()
        far = fp / (fp + tn) if (fp + tn) > 0 else 0
        frr = fn / (fn + tp) if (fn + tp) > 0 else 0
        far_list.append(far)
        frr_list.append(frr)

    plt.figure(figsize=(8, 5))
    plt.plot(thresholds, far_list, label='FAR', linewidth=2)
    plt.plot(thresholds, frr_list, label='FRR', linewidth=2)
    plt.xlabel('Threshold')
    plt.ylabel('Rate')
    plt.title('FAR and FRR vs Threshold')
    plt.legend()
    plt.grid(True)
    plt.tight_layout()
    plt.savefig(os.path.join(output_dir, 'far_vs_threshold.png'))
    plt.close()

def plot_precision_recall_curve(det_df, output_dir):
    """Generate Precision-Recall curve."""
    if 'confidence' not in det_df.columns:
        print("No confidence column; cannot plot PR curve.")
        return
    # Filter out placeholder rows
    mask = det_df['true_label'] != '?'
    plot_df = det_df[mask]
    if plot_df.empty:
        print("No valid rows for PR curve.")
        return

    true_binary = (plot_df['true_label'] == 'authorized').astype(int)
    scores = plot_df['confidence']
    precision, recall, _ = precision_recall_curve(true_binary, scores)
    plt.figure(figsize=(7, 6))
    plt.plot(recall, precision, marker='.', label='PR Curve')
    plt.xlabel('Recall')
    plt.ylabel('Precision')
    plt.title('Precision-Recall Curve')
    plt.grid(True)
    plt.legend()
    plt.tight_layout()
    plt.savefig(os.path.join(output_dir, 'precision_recall_curve.png'))
    plt.close()

def generate_report(metrics, output_dir):
    """Write a text report with metrics and insights."""
    report_path = os.path.join(output_dir, 'analysis_report.txt')
    with open(report_path, 'w') as f:
        f.write("Security System Performance Analysis Report\n")
        f.write("===========================================\n\n")
        f.write(f"Date: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}\n\n")
        f.write("Performance Metrics:\n")
        f.write(f"  Accuracy  : {metrics['Accuracy']:.4f}\n")
        f.write(f"  Precision : {metrics['Precision']:.4f}\n")
        f.write(f"  Recall    : {metrics['Recall']:.4f}\n")
        f.write(f"  F1-score  : {metrics['F1-score']:.4f}\n")
        f.write(f"  FAR       : {metrics['FAR']:.4f}\n")
        f.write(f"  FRR       : {metrics['FRR']:.4f}\n")
        f.write(f"\nConfusion Matrix:\n")
        f.write(f"  True Positives  (Authorized correctly accepted): {metrics['TP']}\n")
        f.write(f"  True Negatives  (Unauthorized correctly rejected): {metrics['TN']}\n")
        f.write(f"  False Positives (Unauthorized accepted): {metrics['FP']}\n")
        f.write(f"  False Negatives (Authorized rejected): {metrics['FN']}\n\n")
        f.write("Insights:\n")
        f.write("  - The system's accuracy of {:.2f}% indicates overall good performance.\n".format(metrics['Accuracy']*100))
        f.write("  - FAR is {:.2f}%, meaning unauthorized access is rare.\n".format(metrics['FAR']*100))
        f.write("  - FRR is {:.2f}%, showing occasional inconvenience for authorized users.\n".format(metrics['FRR']*100))
        f.write("  - The Precision-Recall curve and FAR/FRR trade-off can guide threshold selection.\n")
        f.write("  - To reduce FAR, consider increasing the decision threshold, but this may increase FRR.\n")
        f.write("  - Retraining the SVM with more challenging negative samples could further improve separation.\n\n")
        f.write("Graphs generated:\n")
        f.write("  - FPS vs Time (fps_vs_time.png)\n")
        f.write("  - Faces Detected vs Time (faces_vs_time.png)\n")
        f.write("  - Confidence Distribution Histogram (confidence_histogram.png)\n")
        f.write("  - Confusion Matrix (confusion_matrix.png)\n")
        f.write("  - FAR vs Threshold (far_vs_threshold.png)\n")
        f.write("  - Precision-Recall Curve (precision_recall_curve.png)\n")
    print(f"Report saved to {report_path}")

def main():
    parser = argparse.ArgumentParser(description='Analyze security system logs.')
    parser.add_argument('--detection_log', default='logs/detection_log.csv',
                        help='Path to detection log CSV')
    parser.add_argument('--performance_log', default='logs/performance_log.csv',
                        help='Path to performance log CSV')
    parser.add_argument('--output_dir', default='analysis_output',
                        help='Directory to save graphs and report')
    args = parser.parse_args()

    os.makedirs(args.output_dir, exist_ok=True)

    # Load data
    det_df, perf_df = load_data(args.detection_log, args.performance_log)
    if det_df is None:
        print("Exiting due to missing detection log.")
        return

    # Check required columns
    required_cols = ['true_label', 'predicted_label']
    for col in required_cols:
        if col not in det_df.columns:
            print(f"Missing required column '{col}' in detection log.")
            return

    try:
        # Compute metrics
        metrics = compute_metrics(det_df)
        print("Performance Metrics:")
        for k, v in metrics.items():
            if k not in ['TP','TN','FP','FN']:
                print(f"  {k}: {v:.4f}")
    except ValueError as e:
        print(f"Error computing metrics: {e}")
        print("Please ensure your detection log contains actual ground truth labels (authorized/unauthorized) for at least some rows.")
        return

    # Generate plots (some plots will automatically filter out placeholder rows)
    plot_fps_vs_time(perf_df, args.output_dir)
    plot_faces_vs_time(det_df, args.output_dir)
    plot_confidence_histogram(det_df, args.output_dir)
    plot_confusion_matrix(metrics, args.output_dir)
    plot_far_vs_threshold(det_df, args.output_dir)
    plot_precision_recall_curve(det_df, args.output_dir)

    # Generate report
    generate_report(metrics, args.output_dir)

    print(f"\nAll analysis completed. Output saved to {args.output_dir}")

if __name__ == "__main__":
    main()#!/usr/bin/env python3
"""
analyze_security.py

Reads detection_log.csv and performance_log.csv generated by security_system.py
and produces:
- Performance metrics (Accuracy, Precision, Recall, F1, FAR, FRR)
- FPS vs Time graph
- Faces Detected vs Time graph
- Confidence Score Distribution histogram
- Confusion Matrix
- FAR vs Threshold graph
- Precision-Recall curve

Usage:
    python analyze_security.py --detection_log logs/detection_log.csv \
                               --performance_log logs/performance_log.csv \
                               --output_dir analysis_output
"""

import argparse
import os
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.metrics import (accuracy_score, precision_score, recall_score,
                             f1_score, confusion_matrix, precision_recall_curve)
from datetime import datetime
import warnings
warnings.filterwarnings('ignore')

def load_data(detection_csv, performance_csv):
    """Load detection and performance logs."""
    try:
        det_df = pd.read_csv(detection_csv)
        det_df['timestamp'] = pd.to_datetime(det_df['timestamp'])
    except Exception as e:
        print(f"Error loading detection log: {e}")
        return None, None

    perf_df = None
    if performance_csv and os.path.exists(performance_csv):
        try:
            perf_df = pd.read_csv(performance_csv)
            perf_df['timestamp'] = pd.to_datetime(perf_df['timestamp'])
        except Exception as e:
            print(f"Error loading performance log: {e}")

    return det_df, perf_df

def compute_metrics(det_df):
    """Compute accuracy, precision, recall, f1, far, frr."""
    # Filter out rows where true_label is placeholder "?"
    if 'true_label' in det_df.columns:
        mask = det_df['true_label'] != '?'
        if not mask.all():
            print(f"Warning: {len(det_df) - mask.sum()} rows have placeholder '?' in true_label. These will be ignored.")
            det_df = det_df[mask]

    if det_df.empty:
        raise ValueError("No valid ground truth rows after removing placeholders. Please replace '?' with actual labels.")

    # Check that we have both classes
    unique_true = det_df['true_label'].unique()
    unique_pred = det_df['predicted_label'].unique()
    print(f"Unique true labels: {unique_true}")
    print(f"Unique predicted labels: {unique_pred}")

    if len(unique_true) < 2:
        raise ValueError(f"True labels contain only one class: {unique_true}. Need both 'authorized' and 'unauthorized'.")

    # Map labels to binary: authorized=1, unauthorized=0
    true_binary = det_df['true_label'].apply(lambda x: 1 if x == 'authorized' else 0)
    pred_binary = det_df['predicted_label'].apply(lambda x: 1 if x == 'authorized' else 0)

    acc = accuracy_score(true_binary, pred_binary)
    prec = precision_score(true_binary, pred_binary, zero_division=0)
    rec = recall_score(true_binary, pred_binary, zero_division=0)
    f1 = f1_score(true_binary, pred_binary, zero_division=0)

    tn, fp, fn, tp = confusion_matrix(true_binary, pred_binary).ravel()
    far = fp / (fp + tn) if (fp + tn) > 0 else 0
    frr = fn / (fn + tp) if (fn + tp) > 0 else 0

    metrics = {
        'Accuracy': acc,
        'Precision': prec,
        'Recall': rec,
        'F1-score': f1,
        'FAR': far,
        'FRR': frr,
        'TP': tp,
        'TN': tn,
        'FP': fp,
        'FN': fn
    }
    return metrics

def plot_fps_vs_time(perf_df, output_dir):
    """Generate FPS vs Time graph."""
    if perf_df is None or perf_df.empty:
        print("No performance data to plot FPS.")
        return
    plt.figure(figsize=(10, 4))
    plt.plot(perf_df['timestamp'], perf_df['fps'], marker='o', linestyle='-')
    plt.xlabel('Time')
    plt.ylabel('Frames per Second (FPS)')
    plt.title('FPS vs Time')
    plt.grid(True)
    plt.xticks(rotation=45)
    plt.tight_layout()
    plt.savefig(os.path.join(output_dir, 'fps_vs_time.png'))
    plt.close()

def plot_faces_vs_time(det_df, output_dir, bin_seconds=60):
    """Generate Faces Detected vs Time graph."""
    if det_df.empty:
        return
    # Resample by time bin
    det_df.set_index('timestamp', inplace=True)
    faces_per_bin = det_df.resample(f'{bin_seconds}S').size()
    plt.figure(figsize=(10, 4))
    plt.plot(faces_per_bin.index, faces_per_bin.values)
    plt.xlabel('Time')
    plt.ylabel('Number of Faces Detected')
    plt.title(f'Faces Detected per {bin_seconds} Seconds')
    plt.grid(True)
    plt.tight_layout()
    plt.savefig(os.path.join(output_dir, 'faces_vs_time.png'))
    plt.close()
    det_df.reset_index(inplace=True)

def plot_confidence_histogram(det_df, output_dir):
    """Generate confidence score distribution histogram."""
    if 'confidence' not in det_df.columns:
        print("No confidence column in detection log.")
        return
    # Filter out rows with placeholder true_label for histogram
    if 'true_label' in det_df.columns:
        mask = det_df['true_label'] != '?'
        plot_df = det_df[mask]
    else:
        plot_df = det_df

    if plot_df.empty:
        print("No valid rows for confidence histogram.")
        return

    plt.figure(figsize=(8, 5))
    sns.histplot(data=plot_df, x='confidence', hue='true_label', kde=True, bins=30)
    plt.xlabel('Confidence Score')
    plt.ylabel('Frequency')
    plt.title('Confidence Distribution by True Label')
    plt.legend(title='True Label')
    plt.tight_layout()
    plt.savefig(os.path.join(output_dir, 'confidence_histogram.png'))
    plt.close()

def plot_confusion_matrix(metrics, output_dir):
    """Generate confusion matrix heatmap."""
    cm = np.array([[metrics['TN'], metrics['FP']],
                   [metrics['FN'], metrics['TP']]])
    plt.figure(figsize=(6, 5))
    sns.heatmap(cm, annot=True, fmt='d', cmap='Blues',
                xticklabels=['Unauthorized', 'Authorized'],
                yticklabels=['Unauthorized', 'Authorized'])
    plt.xlabel('Predicted')
    plt.ylabel('True')
    plt.title('Confusion Matrix')
    plt.tight_layout()
    plt.savefig(os.path.join(output_dir, 'confusion_matrix.png'))
    plt.close()

def plot_far_vs_threshold(det_df, output_dir):
    """Generate FAR vs Threshold graph."""
    if 'confidence' not in det_df.columns:
        print("No confidence column; cannot plot FAR vs Threshold.")
        return
    # Filter out placeholder rows
    mask = det_df['true_label'] != '?'
    plot_df = det_df[mask]
    if plot_df.empty:
        print("No valid rows for FAR vs Threshold.")
        return

    true_binary = (plot_df['true_label'] == 'authorized').astype(int)
    thresholds = np.linspace(0, 1, 100)
    far_list = []
    frr_list = []
    for th in thresholds:
        pred = (plot_df['confidence'] >= th).astype(int)
        tn, fp, fn, tp = confusion_matrix(true_binary, pred).ravel()
        far = fp / (fp + tn) if (fp + tn) > 0 else 0
        frr = fn / (fn + tp) if (fn + tp) > 0 else 0
        far_list.append(far)
        frr_list.append(frr)

    plt.figure(figsize=(8, 5))
    plt.plot(thresholds, far_list, label='FAR', linewidth=2)
    plt.plot(thresholds, frr_list, label='FRR', linewidth=2)
    plt.xlabel('Threshold')
    plt.ylabel('Rate')
    plt.title('FAR and FRR vs Threshold')
    plt.legend()
    plt.grid(True)
    plt.tight_layout()
    plt.savefig(os.path.join(output_dir, 'far_vs_threshold.png'))
    plt.close()

def plot_precision_recall_curve(det_df, output_dir):
    """Generate Precision-Recall curve."""
    if 'confidence' not in det_df.columns:
        print("No confidence column; cannot plot PR curve.")
        return
    # Filter out placeholder rows
    mask = det_df['true_label'] != '?'
    plot_df = det_df[mask]
    if plot_df.empty:
        print("No valid rows for PR curve.")
        return

    true_binary = (plot_df['true_label'] == 'authorized').astype(int)
    scores = plot_df['confidence']
    precision, recall, _ = precision_recall_curve(true_binary, scores)
    plt.figure(figsize=(7, 6))
    plt.plot(recall, precision, marker='.', label='PR Curve')
    plt.xlabel('Recall')
    plt.ylabel('Precision')
    plt.title('Precision-Recall Curve')
    plt.grid(True)
    plt.legend()
    plt.tight_layout()
    plt.savefig(os.path.join(output_dir, 'precision_recall_curve.png'))
    plt.close()

def generate_report(metrics, output_dir):
    """Write a text report with metrics and insights."""
    report_path = os.path.join(output_dir, 'analysis_report.txt')
    with open(report_path, 'w') as f:
        f.write("Security System Performance Analysis Report\n")
        f.write("===========================================\n\n")
        f.write(f"Date: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}\n\n")
        f.write("Performance Metrics:\n")
        f.write(f"  Accuracy  : {metrics['Accuracy']:.4f}\n")
        f.write(f"  Precision : {metrics['Precision']:.4f}\n")
        f.write(f"  Recall    : {metrics['Recall']:.4f}\n")
        f.write(f"  F1-score  : {metrics['F1-score']:.4f}\n")
        f.write(f"  FAR       : {metrics['FAR']:.4f}\n")
        f.write(f"  FRR       : {metrics['FRR']:.4f}\n")
        f.write(f"\nConfusion Matrix:\n")
        f.write(f"  True Positives  (Authorized correctly accepted): {metrics['TP']}\n")
        f.write(f"  True Negatives  (Unauthorized correctly rejected): {metrics['TN']}\n")
        f.write(f"  False Positives (Unauthorized accepted): {metrics['FP']}\n")
        f.write(f"  False Negatives (Authorized rejected): {metrics['FN']}\n\n")
        f.write("Insights:\n")
        f.write("  - The system's accuracy of {:.2f}% indicates overall good performance.\n".format(metrics['Accuracy']*100))
        f.write("  - FAR is {:.2f}%, meaning unauthorized access is rare.\n".format(metrics['FAR']*100))
        f.write("  - FRR is {:.2f}%, showing occasional inconvenience for authorized users.\n".format(metrics['FRR']*100))
        f.write("  - The Precision-Recall curve and FAR/FRR trade-off can guide threshold selection.\n")
        f.write("  - To reduce FAR, consider increasing the decision threshold, but this may increase FRR.\n")
        f.write("  - Retraining the SVM with more challenging negative samples could further improve separation.\n\n")
        f.write("Graphs generated:\n")
        f.write("  - FPS vs Time (fps_vs_time.png)\n")
        f.write("  - Faces Detected vs Time (faces_vs_time.png)\n")
        f.write("  - Confidence Distribution Histogram (confidence_histogram.png)\n")
        f.write("  - Confusion Matrix (confusion_matrix.png)\n")
        f.write("  - FAR vs Threshold (far_vs_threshold.png)\n")
        f.write("  - Precision-Recall Curve (precision_recall_curve.png)\n")
    print(f"Report saved to {report_path}")

def main():
    parser = argparse.ArgumentParser(description='Analyze security system logs.')
    parser.add_argument('--detection_log', default='logs/detection_log.csv',
                        help='Path to detection log CSV')
    parser.add_argument('--performance_log', default='logs/performance_log.csv',
                        help='Path to performance log CSV')
    parser.add_argument('--output_dir', default='analysis_output',
                        help='Directory to save graphs and report')
    args = parser.parse_args()

    os.makedirs(args.output_dir, exist_ok=True)

    # Load data
    det_df, perf_df = load_data(args.detection_log, args.performance_log)
    if det_df is None:
        print("Exiting due to missing detection log.")
        return

    # Check required columns
    required_cols = ['true_label', 'predicted_label']
    for col in required_cols:
        if col not in det_df.columns:
            print(f"Missing required column '{col}' in detection log.")
            return

    try:
        # Compute metrics
        metrics = compute_metrics(det_df)
        print("Performance Metrics:")
        for k, v in metrics.items():
            if k not in ['TP','TN','FP','FN']:
                print(f"  {k}: {v:.4f}")
    except ValueError as e:
        print(f"Error computing metrics: {e}")
        print("Please ensure your detection log contains actual ground truth labels (authorized/unauthorized) for at least some rows.")
        return

    # Generate plots (some plots will automatically filter out placeholder rows)
    plot_fps_vs_time(perf_df, args.output_dir)
    plot_faces_vs_time(det_df, args.output_dir)
    plot_confidence_histogram(det_df, args.output_dir)
    plot_confusion_matrix(metrics, args.output_dir)
    plot_far_vs_threshold(det_df, args.output_dir)
    plot_precision_recall_curve(det_df, args.output_dir)

    # Generate report
    generate_report(metrics, args.output_dir)

    print(f"\nAll analysis completed. Output saved to {args.output_dir}")

if __name__ == "__main__":
    main()